### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by jjgonecrypto** [comment]
Hey @Piterden I'd be happy to take this but we'd need a new screenshot as well. If you get a chance could you update the PR with one? Otherwise let me know and I can do it later today.

**Comment by Piterden** [comment]
I had tried to paste the image, but couldn't 
selection_361

**Comment by jjgonecrypto** [comment]
That works above no? (I just edited it slightly)

**Comment by jjgonecrypto** [comment]
(I can update the README after merging this PR though as well with that image if it's easier)

**Comment by Piterden** [comment]
Now you have the screenshot. Could you add it yourself, please

**Pull request closed without merging**
